server:
  port: 9000

amazon:
  dynamodb:
    endpoint: http://localhost:8000
  aws:
    accesskey: ''
    secretkey: ''

spring:
  datasource:
    continueOnError: true
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb

  social:
    facebook:
      app-id: 196631884151165
      app-secret: 038fa15520e5875f13de245bc5f5132e
    google:
      app-id: 614478737-jdlvuj1esql0dpkq5hu2jss2ipbmfmdf.apps.googleusercontent.com
      app-secret: KhG4x6Ko64iKMT6PJqnTapWl

